var nameList = [
  "Aarav",
  "Aarush",
  "Advik",
  "Aadi",
  "Aarav",
  "Vihaan",
  "Arjun",
  "Reyansh",
  "Mohammed",
  "Mohammad",
  "Mohd",
  "Arnav",
  "Ayaan",
  "Kabir",
  "Krishna",
  "Ranveer",
  "Zayan",
  "Shaurya",
  "Sai",
  "Atharva",
  "Rudra",
  "Reyansh",
  "Pranav",
  "Aryan",
  "Dhruv",
  "Arush",
  "Ishaan",
  "Vivaan",
  "Vivaan",
  "Hriday",
  "Vihaan",
  "Abeer",
  "Hridaan",
  "Kian",
  "Anay",
  "Rian",
  "Ahaan",
  "Yuvan",
  "Samarth",
  "Daksh",
  "Darsh",
  "Yash",
  "Parth",
  "Vedant",
  "Shivansh",
  "Veer",
  "Aditya",
  "Kabir",
  "Advaith",
  "Shaarav",
  "Riaan",
  "Prayansh",
  "Avyan",
  "Abeer",
  "Shreyansh",
  "Mohammed",
  "Mohammad",
  "Mohd",
  "Samaira",
  "Anaya",
  "Myra",
  "Avni",
  "Anika",
  "Aadhya",
  "Advika",
  "Avishi",
  "Zara",
  "Siya",
  "Anvi",
  "Aradhya",
  "Ridhi",
  "Maira",
  "Kiara",
  "Diya",
  "Anaya",
  "Aaradhya",
  "Kyra",
  "Maria",
  "Aahana",
  "Saanvi",
  "Anvika",
  "Anvaya",
  "Myra",
  "Iraa",
  "Anvi",
  "Aarohi",
  "Amaira",
  "Navya",
  "Anaisha",
  "Anvika",
  "Amaya",
  "Aashi",
  "Ariana",
  "Tanisha",
  "Aditi",
  "Sia",
  "Kavya",
  "Hiya",
  "Navya",
  "Shreya",
  "Mysha",
  "Saisha",
  "Kiara",
  "Anaaya",
  "Nia",
  "Iva",
  "Avisha",
  "Shanaya",
  "Pari",
  "Riya",
  "Ridhima",
  "Anisha",
  "Aanya",
  "Anvi",
  "Saanvi",
  "Hoorain",
  "Aarna",
  "Viha",
  "Anushka",
  "Myra",
  "Kashvi",
  "Risha",
  "Riddhi",
  "Aashvi",
  "Aarvi",
  "Anaisha",
  "Ahaana",
  "Anvi",
  "Riva",
  "Aarvi",
  "Anvaya",
  "Kiara",
  "Anshika",
  "Arisha",
  "Rutvi",
  "Miraya",
  "Aarna",
  "Ranveer",
  "Mohammed",
  "Mohammad",
  "Mohd",
  "Aarav",
  "Aarush",
  "Advik",
  "Aadi",
  "Aarav",
  "Vihaan",
  "Arjun",
  "Reyansh",
  "Mohammed",
  "Mohammad",
  "Mohd",
  "Arnav",
  "Ayaan",
  "Kabir",
  "Krishna",
  "Ranveer",
  "Zayan",
  "Shaurya",
  "Sai",
  "Atharva",
  "Rudra",
  "Reyansh",
  "Pranav",
  "Aryan",
  "Dhruv",
  "Arush",
  "Ishaan",
  "Vivaan",
  "Vivaan",
  "Hriday",
  "Vihaan",
  "Abeer",
  "Hridaan",
  "Kian",
  "Anay",
  "Rian",
  "Ahaan",
  "Yuvan",
  "Samarth",
  "Daksh",
  "Darsh",
  "Yash",
  "Parth",
  "Vedant",
  "Shivansh",
  "Veer",
  "Aditya",
  "Kabir",
  "Advaith",
  "Shaarav",
  "Riaan",
  "Prayansh",
  "Avyan",
  "Abeer",
  "Shreyansh",
  "Mohammed",
  "Mohammad",
  "Mohd",
  "Samaira",
  "Anaya",
  "Myra",
  "Avni",
  "Anika",
  "Aadhya",
  "Advika",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const responses = [
  "Hello everyone!",
  "Nice to see you here!",
  "What are your thoughts on this?",
  "I love this stream!",
  "Can someone explain this to me?",
  "Who else is excited?",
  "This is amazing!",
  "I have a question...",
  "Any predictions for the next part?",
  "Let's get this party started!",
  "Where are you all from?",
  "This is so much fun!",
  "I'm new here, what's happening?",
  "Whoa, that was unexpected!",
  "I can't wait for the next part!",
  "Does anyone know the answer?",
  "This stream is lit!",
  "I'm loving every moment!",
  "Who else is binge-watching?",
  "This is epic!",
  "I'm hooked!",
  "I need to catch up on previous episodes!",
  "Who's your favorite character?",
  "This is so addictive!",
  "I can't stop watching!",
  "Where has this been all my life?",
  "I'm totally invested in this!",
  "I need more!",
  "I'm on the edge of my seat!",
  "Who's with me?",
  "This stream is everything!",
  "What a plot twist!",
  "I'm dying to know what happens next!",
  "This is better than I expected!",
  "Who else is obsessed?",
  "I'm living for this!",
  "Who's ready for the finale?",
  "I'm already rewatching!",
  "I can't get enough!",
  "This stream deserves an award!",
  "Who else is staying up all night?",
  "I'm telling all my friends about this!",
  "Who's your OTP?",
  "I need tissues!",
  "This is going to be legendary!",
  "I'm emotionally invested!",
  "This stream is pure gold!",
  "Who's got theories?",
  "I'm already planning a rewatch!",
];
export const respond = () =>
  responses[Math.floor(Math.random() * responses.length)];
